# Generated by Django 5.0.6 on 2024-10-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inscripcionpractica',
            table='public.estudiante_inscripcionpractica',
        ),
    ]
