# Generated by Django 5.0.6 on 2024-10-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_alter_inscripcionpractica_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inscripcionpractica',
            table='estudiante_inscripcionpractica',
        ),
    ]
