# Generated by Django 4.1.13 on 2024-10-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='coordinador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
